### ISSUE TITLE
List of a UnicodeEnumAttribute

### ISSUE THREAD

**Issue by Seluj78** [lyft/pynamodb-attributes#47]
Hi,

First of all, thank you very much for this lib, it's really useful !

I cannot find a way to make a UnicodeEnumAttribute work in a ListAttribute, and I was wondering if it was a bug or not.

Cheers !

```py
    flags = ListAttribute(of=UnicodeEnumAttribute, null=True, default=[])  # Raises TypeError: __init__() missing 1 required positional argument: 'enum_type'
    flags = ListAttribute(of=UnicodeEnumAttribute(UserFlagEnum), null=True, default=[])  # Raises TypeError: issubclass() arg 1 must be a class
```

**Comment by Seluj78** [comment]
Ping :)

**Comment by rayaankha-tara** [comment]
hey there! I wanted to achieve the same objective and I opted to subclass `UnicodeEnumAttribute` and provide that as the class to `ListAttribute`. This is the implementation I went with. I'll use your class names to structure my answer. 

This `UnicodeEnumAttribute(UserFlagEnum)` doesn't work since it creates an object not a class, so I went with the following solution

```
class UserFlagEnum(str, Enum):
	SOME_FLAG: "SOME_FLAG"
	NOT_SOME_FLAG: "NOT_SOME_FLAG"
    
class UserFlagAttribute(UnicodeEnumAttribute):
	def __init__(self, **kwargs: Any) -> None:
        super().__init__(enum_type=UserFlagEnum, **kwargs)
           
```

Then, you can specify

```
flags = ListAttribute(of=UserFlagAttribute, null=True, default=[])
```

So now, the error message you got `__init__() missing 1 required positional argument: 'enum_type'` won't happen since `UserFlagAttribute.__init__` doesn't require a positional argument an in turn supplies the `enum_type` positional argument to `UnicodeEnumAttribute.__init__`

**Comment by Seluj78** [comment]
Oh wow thank you very much ! I don't know if we'll need it now since we're currently migrating our database to SQL instead of DynamoDB but I am definitely keeping that in mind for the future !

Thanks again for your time spent on the matter !
